/*
 * ngDesk_Operations
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Reminder
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T21:25:05.928Z")
public class Reminder {
  @SerializedName("TICKET_REMINDER_ID")
  private Integer TICKET_REMINDER_ID = null;

  @SerializedName("TICKET_ID")
  private Integer TICKET_ID = null;

  @SerializedName("INTERVAL")
  private Integer INTERVAL = null;

  @SerializedName("RECURRENCE")
  private Integer RECURRENCE = null;

  @SerializedName("TYPE")
  private String TYPE = null;

  @SerializedName("DATE_CREATED")
  private String DATE_CREATED = null;

  public Reminder TICKET_REMINDER_ID(Integer TICKET_REMINDER_ID) {
    this.TICKET_REMINDER_ID = TICKET_REMINDER_ID;
    return this;
  }

   /**
   * Get TICKET_REMINDER_ID
   * @return TICKET_REMINDER_ID
  **/
  @ApiModelProperty(value = "")
  public Integer getTICKETREMINDERID() {
    return TICKET_REMINDER_ID;
  }

  public void setTICKETREMINDERID(Integer TICKET_REMINDER_ID) {
    this.TICKET_REMINDER_ID = TICKET_REMINDER_ID;
  }

  public Reminder TICKET_ID(Integer TICKET_ID) {
    this.TICKET_ID = TICKET_ID;
    return this;
  }

   /**
   * Get TICKET_ID
   * @return TICKET_ID
  **/
  @ApiModelProperty(value = "")
  public Integer getTICKETID() {
    return TICKET_ID;
  }

  public void setTICKETID(Integer TICKET_ID) {
    this.TICKET_ID = TICKET_ID;
  }

  public Reminder INTERVAL(Integer INTERVAL) {
    this.INTERVAL = INTERVAL;
    return this;
  }

   /**
   * Get INTERVAL
   * @return INTERVAL
  **/
  @ApiModelProperty(value = "")
  public Integer getINTERVAL() {
    return INTERVAL;
  }

  public void setINTERVAL(Integer INTERVAL) {
    this.INTERVAL = INTERVAL;
  }

  public Reminder RECURRENCE(Integer RECURRENCE) {
    this.RECURRENCE = RECURRENCE;
    return this;
  }

   /**
   * Get RECURRENCE
   * @return RECURRENCE
  **/
  @ApiModelProperty(value = "")
  public Integer getRECURRENCE() {
    return RECURRENCE;
  }

  public void setRECURRENCE(Integer RECURRENCE) {
    this.RECURRENCE = RECURRENCE;
  }

  public Reminder TYPE(String TYPE) {
    this.TYPE = TYPE;
    return this;
  }

   /**
   * Get TYPE
   * @return TYPE
  **/
  @ApiModelProperty(value = "")
  public String getTYPE() {
    return TYPE;
  }

  public void setTYPE(String TYPE) {
    this.TYPE = TYPE;
  }

  public Reminder DATE_CREATED(String DATE_CREATED) {
    this.DATE_CREATED = DATE_CREATED;
    return this;
  }

   /**
   * Get DATE_CREATED
   * @return DATE_CREATED
  **/
  @ApiModelProperty(value = "")
  public String getDATECREATED() {
    return DATE_CREATED;
  }

  public void setDATECREATED(String DATE_CREATED) {
    this.DATE_CREATED = DATE_CREATED;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Reminder reminder = (Reminder) o;
    return Objects.equals(this.TICKET_REMINDER_ID, reminder.TICKET_REMINDER_ID) &&
        Objects.equals(this.TICKET_ID, reminder.TICKET_ID) &&
        Objects.equals(this.INTERVAL, reminder.INTERVAL) &&
        Objects.equals(this.RECURRENCE, reminder.RECURRENCE) &&
        Objects.equals(this.TYPE, reminder.TYPE) &&
        Objects.equals(this.DATE_CREATED, reminder.DATE_CREATED);
  }

  @Override
  public int hashCode() {
    return Objects.hash(TICKET_REMINDER_ID, TICKET_ID, INTERVAL, RECURRENCE, TYPE, DATE_CREATED);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Reminder {\n");
    
    sb.append("    TICKET_REMINDER_ID: ").append(toIndentedString(TICKET_REMINDER_ID)).append("\n");
    sb.append("    TICKET_ID: ").append(toIndentedString(TICKET_ID)).append("\n");
    sb.append("    INTERVAL: ").append(toIndentedString(INTERVAL)).append("\n");
    sb.append("    RECURRENCE: ").append(toIndentedString(RECURRENCE)).append("\n");
    sb.append("    TYPE: ").append(toIndentedString(TYPE)).append("\n");
    sb.append("    DATE_CREATED: ").append(toIndentedString(DATE_CREATED)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

