/*
 * ngDesk_Operations
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TicketMessage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * Ticket
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T21:25:05.928Z")
public class Ticket {
  @SerializedName("TICKET_ID")
  private Integer TICKET_ID = null;

  @SerializedName("SUBJECT")
  private String SUBJECT = null;

  @SerializedName("DATE_REQUIRED_BY")
  private DateTime DATE_REQUIRED_BY = null;

  @SerializedName("SEVERITY")
  private String SEVERITY = null;

  @SerializedName("DATE_CREATED")
  private DateTime DATE_CREATED = null;

  @SerializedName("SOURCE")
  private String SOURCE = null;

  @SerializedName("TICKET_UUID")
  private String TICKET_UUID = null;

  @SerializedName("STATUS")
  private String STATUS = null;

  @SerializedName("IS_INTERNAL")
  private String IS_INTERNAL = null;

  @SerializedName("REQUESTOR_GROUP_USER_ID")
  private Integer REQUESTOR_GROUP_USER_ID = null;

  @SerializedName("ASSIGNEE_GROUP_USER_ID")
  private Integer ASSIGNEE_GROUP_USER_ID = null;

  @SerializedName("OWNER_GROUP_USER_ID")
  private Integer OWNER_GROUP_USER_ID = null;

  @SerializedName("REQUESTOR_NAME")
  private String REQUESTOR_NAME = null;

  @SerializedName("OWNER_NAME")
  private String OWNER_NAME = null;

  @SerializedName("ASSIGNEE_NAME")
  private String ASSIGNEE_NAME = null;

  @SerializedName("OWNER_ACCOUNT_NAME")
  private String OWNER_ACCOUNT_NAME = null;

  @SerializedName("TICKET_MESSAGES")
  private List<TicketMessage> TICKET_MESSAGES = null;

  public Ticket TICKET_ID(Integer TICKET_ID) {
    this.TICKET_ID = TICKET_ID;
    return this;
  }

   /**
   * Get TICKET_ID
   * @return TICKET_ID
  **/
  @ApiModelProperty(value = "")
  public Integer getTICKETID() {
    return TICKET_ID;
  }

  public void setTICKETID(Integer TICKET_ID) {
    this.TICKET_ID = TICKET_ID;
  }

  public Ticket SUBJECT(String SUBJECT) {
    this.SUBJECT = SUBJECT;
    return this;
  }

   /**
   * Get SUBJECT
   * @return SUBJECT
  **/
  @ApiModelProperty(value = "")
  public String getSUBJECT() {
    return SUBJECT;
  }

  public void setSUBJECT(String SUBJECT) {
    this.SUBJECT = SUBJECT;
  }

  public Ticket DATE_REQUIRED_BY(DateTime DATE_REQUIRED_BY) {
    this.DATE_REQUIRED_BY = DATE_REQUIRED_BY;
    return this;
  }

   /**
   * Get DATE_REQUIRED_BY
   * @return DATE_REQUIRED_BY
  **/
  @ApiModelProperty(value = "")
  public DateTime getDATEREQUIREDBY() {
    return DATE_REQUIRED_BY;
  }

  public void setDATEREQUIREDBY(DateTime DATE_REQUIRED_BY) {
    this.DATE_REQUIRED_BY = DATE_REQUIRED_BY;
  }

  public Ticket SEVERITY(String SEVERITY) {
    this.SEVERITY = SEVERITY;
    return this;
  }

   /**
   * Get SEVERITY
   * @return SEVERITY
  **/
  @ApiModelProperty(value = "")
  public String getSEVERITY() {
    return SEVERITY;
  }

  public void setSEVERITY(String SEVERITY) {
    this.SEVERITY = SEVERITY;
  }

  public Ticket DATE_CREATED(DateTime DATE_CREATED) {
    this.DATE_CREATED = DATE_CREATED;
    return this;
  }

   /**
   * Get DATE_CREATED
   * @return DATE_CREATED
  **/
  @ApiModelProperty(value = "")
  public DateTime getDATECREATED() {
    return DATE_CREATED;
  }

  public void setDATECREATED(DateTime DATE_CREATED) {
    this.DATE_CREATED = DATE_CREATED;
  }

  public Ticket SOURCE(String SOURCE) {
    this.SOURCE = SOURCE;
    return this;
  }

   /**
   * Get SOURCE
   * @return SOURCE
  **/
  @ApiModelProperty(value = "")
  public String getSOURCE() {
    return SOURCE;
  }

  public void setSOURCE(String SOURCE) {
    this.SOURCE = SOURCE;
  }

  public Ticket TICKET_UUID(String TICKET_UUID) {
    this.TICKET_UUID = TICKET_UUID;
    return this;
  }

   /**
   * Get TICKET_UUID
   * @return TICKET_UUID
  **/
  @ApiModelProperty(value = "")
  public String getTICKETUUID() {
    return TICKET_UUID;
  }

  public void setTICKETUUID(String TICKET_UUID) {
    this.TICKET_UUID = TICKET_UUID;
  }

  public Ticket STATUS(String STATUS) {
    this.STATUS = STATUS;
    return this;
  }

   /**
   * Get STATUS
   * @return STATUS
  **/
  @ApiModelProperty(value = "")
  public String getSTATUS() {
    return STATUS;
  }

  public void setSTATUS(String STATUS) {
    this.STATUS = STATUS;
  }

  public Ticket IS_INTERNAL(String IS_INTERNAL) {
    this.IS_INTERNAL = IS_INTERNAL;
    return this;
  }

   /**
   * Get IS_INTERNAL
   * @return IS_INTERNAL
  **/
  @ApiModelProperty(value = "")
  public String getISINTERNAL() {
    return IS_INTERNAL;
  }

  public void setISINTERNAL(String IS_INTERNAL) {
    this.IS_INTERNAL = IS_INTERNAL;
  }

  public Ticket REQUESTOR_GROUP_USER_ID(Integer REQUESTOR_GROUP_USER_ID) {
    this.REQUESTOR_GROUP_USER_ID = REQUESTOR_GROUP_USER_ID;
    return this;
  }

   /**
   * Get REQUESTOR_GROUP_USER_ID
   * @return REQUESTOR_GROUP_USER_ID
  **/
  @ApiModelProperty(value = "")
  public Integer getREQUESTORGROUPUSERID() {
    return REQUESTOR_GROUP_USER_ID;
  }

  public void setREQUESTORGROUPUSERID(Integer REQUESTOR_GROUP_USER_ID) {
    this.REQUESTOR_GROUP_USER_ID = REQUESTOR_GROUP_USER_ID;
  }

  public Ticket ASSIGNEE_GROUP_USER_ID(Integer ASSIGNEE_GROUP_USER_ID) {
    this.ASSIGNEE_GROUP_USER_ID = ASSIGNEE_GROUP_USER_ID;
    return this;
  }

   /**
   * Get ASSIGNEE_GROUP_USER_ID
   * @return ASSIGNEE_GROUP_USER_ID
  **/
  @ApiModelProperty(value = "")
  public Integer getASSIGNEEGROUPUSERID() {
    return ASSIGNEE_GROUP_USER_ID;
  }

  public void setASSIGNEEGROUPUSERID(Integer ASSIGNEE_GROUP_USER_ID) {
    this.ASSIGNEE_GROUP_USER_ID = ASSIGNEE_GROUP_USER_ID;
  }

  public Ticket OWNER_GROUP_USER_ID(Integer OWNER_GROUP_USER_ID) {
    this.OWNER_GROUP_USER_ID = OWNER_GROUP_USER_ID;
    return this;
  }

   /**
   * Get OWNER_GROUP_USER_ID
   * @return OWNER_GROUP_USER_ID
  **/
  @ApiModelProperty(value = "")
  public Integer getOWNERGROUPUSERID() {
    return OWNER_GROUP_USER_ID;
  }

  public void setOWNERGROUPUSERID(Integer OWNER_GROUP_USER_ID) {
    this.OWNER_GROUP_USER_ID = OWNER_GROUP_USER_ID;
  }

  public Ticket REQUESTOR_NAME(String REQUESTOR_NAME) {
    this.REQUESTOR_NAME = REQUESTOR_NAME;
    return this;
  }

   /**
   * Get REQUESTOR_NAME
   * @return REQUESTOR_NAME
  **/
  @ApiModelProperty(value = "")
  public String getREQUESTORNAME() {
    return REQUESTOR_NAME;
  }

  public void setREQUESTORNAME(String REQUESTOR_NAME) {
    this.REQUESTOR_NAME = REQUESTOR_NAME;
  }

  public Ticket OWNER_NAME(String OWNER_NAME) {
    this.OWNER_NAME = OWNER_NAME;
    return this;
  }

   /**
   * Get OWNER_NAME
   * @return OWNER_NAME
  **/
  @ApiModelProperty(value = "")
  public String getOWNERNAME() {
    return OWNER_NAME;
  }

  public void setOWNERNAME(String OWNER_NAME) {
    this.OWNER_NAME = OWNER_NAME;
  }

  public Ticket ASSIGNEE_NAME(String ASSIGNEE_NAME) {
    this.ASSIGNEE_NAME = ASSIGNEE_NAME;
    return this;
  }

   /**
   * Get ASSIGNEE_NAME
   * @return ASSIGNEE_NAME
  **/
  @ApiModelProperty(value = "")
  public String getASSIGNEENAME() {
    return ASSIGNEE_NAME;
  }

  public void setASSIGNEENAME(String ASSIGNEE_NAME) {
    this.ASSIGNEE_NAME = ASSIGNEE_NAME;
  }

  public Ticket OWNER_ACCOUNT_NAME(String OWNER_ACCOUNT_NAME) {
    this.OWNER_ACCOUNT_NAME = OWNER_ACCOUNT_NAME;
    return this;
  }

   /**
   * Get OWNER_ACCOUNT_NAME
   * @return OWNER_ACCOUNT_NAME
  **/
  @ApiModelProperty(value = "")
  public String getOWNERACCOUNTNAME() {
    return OWNER_ACCOUNT_NAME;
  }

  public void setOWNERACCOUNTNAME(String OWNER_ACCOUNT_NAME) {
    this.OWNER_ACCOUNT_NAME = OWNER_ACCOUNT_NAME;
  }

  public Ticket TICKET_MESSAGES(List<TicketMessage> TICKET_MESSAGES) {
    this.TICKET_MESSAGES = TICKET_MESSAGES;
    return this;
  }

  public Ticket addTICKETMESSAGESItem(TicketMessage TICKET_MESSAGESItem) {
    if (this.TICKET_MESSAGES == null) {
      this.TICKET_MESSAGES = new ArrayList<TicketMessage>();
    }
    this.TICKET_MESSAGES.add(TICKET_MESSAGESItem);
    return this;
  }

   /**
   * Get TICKET_MESSAGES
   * @return TICKET_MESSAGES
  **/
  @ApiModelProperty(value = "")
  public List<TicketMessage> getTICKETMESSAGES() {
    return TICKET_MESSAGES;
  }

  public void setTICKETMESSAGES(List<TicketMessage> TICKET_MESSAGES) {
    this.TICKET_MESSAGES = TICKET_MESSAGES;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ticket ticket = (Ticket) o;
    return Objects.equals(this.TICKET_ID, ticket.TICKET_ID) &&
        Objects.equals(this.SUBJECT, ticket.SUBJECT) &&
        Objects.equals(this.DATE_REQUIRED_BY, ticket.DATE_REQUIRED_BY) &&
        Objects.equals(this.SEVERITY, ticket.SEVERITY) &&
        Objects.equals(this.DATE_CREATED, ticket.DATE_CREATED) &&
        Objects.equals(this.SOURCE, ticket.SOURCE) &&
        Objects.equals(this.TICKET_UUID, ticket.TICKET_UUID) &&
        Objects.equals(this.STATUS, ticket.STATUS) &&
        Objects.equals(this.IS_INTERNAL, ticket.IS_INTERNAL) &&
        Objects.equals(this.REQUESTOR_GROUP_USER_ID, ticket.REQUESTOR_GROUP_USER_ID) &&
        Objects.equals(this.ASSIGNEE_GROUP_USER_ID, ticket.ASSIGNEE_GROUP_USER_ID) &&
        Objects.equals(this.OWNER_GROUP_USER_ID, ticket.OWNER_GROUP_USER_ID) &&
        Objects.equals(this.REQUESTOR_NAME, ticket.REQUESTOR_NAME) &&
        Objects.equals(this.OWNER_NAME, ticket.OWNER_NAME) &&
        Objects.equals(this.ASSIGNEE_NAME, ticket.ASSIGNEE_NAME) &&
        Objects.equals(this.OWNER_ACCOUNT_NAME, ticket.OWNER_ACCOUNT_NAME) &&
        Objects.equals(this.TICKET_MESSAGES, ticket.TICKET_MESSAGES);
  }

  @Override
  public int hashCode() {
    return Objects.hash(TICKET_ID, SUBJECT, DATE_REQUIRED_BY, SEVERITY, DATE_CREATED, SOURCE, TICKET_UUID, STATUS, IS_INTERNAL, REQUESTOR_GROUP_USER_ID, ASSIGNEE_GROUP_USER_ID, OWNER_GROUP_USER_ID, REQUESTOR_NAME, OWNER_NAME, ASSIGNEE_NAME, OWNER_ACCOUNT_NAME, TICKET_MESSAGES);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ticket {\n");
    
    sb.append("    TICKET_ID: ").append(toIndentedString(TICKET_ID)).append("\n");
    sb.append("    SUBJECT: ").append(toIndentedString(SUBJECT)).append("\n");
    sb.append("    DATE_REQUIRED_BY: ").append(toIndentedString(DATE_REQUIRED_BY)).append("\n");
    sb.append("    SEVERITY: ").append(toIndentedString(SEVERITY)).append("\n");
    sb.append("    DATE_CREATED: ").append(toIndentedString(DATE_CREATED)).append("\n");
    sb.append("    SOURCE: ").append(toIndentedString(SOURCE)).append("\n");
    sb.append("    TICKET_UUID: ").append(toIndentedString(TICKET_UUID)).append("\n");
    sb.append("    STATUS: ").append(toIndentedString(STATUS)).append("\n");
    sb.append("    IS_INTERNAL: ").append(toIndentedString(IS_INTERNAL)).append("\n");
    sb.append("    REQUESTOR_GROUP_USER_ID: ").append(toIndentedString(REQUESTOR_GROUP_USER_ID)).append("\n");
    sb.append("    ASSIGNEE_GROUP_USER_ID: ").append(toIndentedString(ASSIGNEE_GROUP_USER_ID)).append("\n");
    sb.append("    OWNER_GROUP_USER_ID: ").append(toIndentedString(OWNER_GROUP_USER_ID)).append("\n");
    sb.append("    REQUESTOR_NAME: ").append(toIndentedString(REQUESTOR_NAME)).append("\n");
    sb.append("    OWNER_NAME: ").append(toIndentedString(OWNER_NAME)).append("\n");
    sb.append("    ASSIGNEE_NAME: ").append(toIndentedString(ASSIGNEE_NAME)).append("\n");
    sb.append("    OWNER_ACCOUNT_NAME: ").append(toIndentedString(OWNER_ACCOUNT_NAME)).append("\n");
    sb.append("    TICKET_MESSAGES: ").append(toIndentedString(TICKET_MESSAGES)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

